### ISSUE TITLE
Document the impact of jekyll-remote-theme more clearly

### ISSUE THREAD

**Issue by aschrijver** [benbalter/jekyll-remote-theme#42]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

I am new to Jekyll and using `jekyll-remote-theme` currently with the excellent Minimal Mistakes theme. But - while following instructions - I am confused about the actual impact of having a remote theme.

What does it do? Do I get automatic updates when the upstream theme changes? How about the customizations I made to it.. will they be overwritten. I cloned the Minimal Mistakes repo, so do I actually need remote theme? Can I leave out a bunch of files in the cloned repo when having it?

### Describe the solution you'd like

It seems the only way to answer the questions above is to go through the code and figure out what it does exactly.

Would be great if the README gave a clear description of this instead, saving lots of time for me and other potential users of your project.

**Comment by mmistakes** [comment]
@aschrijver The benefit of a remote theme is you don't have to maintain a copy of the theme's files in your repo (`_layouts`, `_includes`, `_sass`, and other assets).

This makes updating much easier. Anytime the theme pushes up changes or enhancements to GitHub, the next time you build your site, remote theme plugin will pull down those updated theme files.

Customizing the theme files [works just as it always has](https://jekyllrb.com/docs/themes/#understanding-gem-based-themes). If you want to alter an include or layout, you add that to your repo and when Jekyll builds it will use that version instead of what is bundled with the theme.

Since you cloned the theme and have all of the theme files there using it as a "remote theme" is pointless. You're essentially overiding each of the theme files. If you've only customized a handful of them I'd suggest keeping and remove everything else.
