### ISSUE TITLE
Cannot use a remote theme on a branch with a "/" in the name

### ISSUE THREAD

**Issue by JesseTG** [benbalter/jekyll-remote-theme#73]
### Describe the bug

When attempting to use a branch of a remote theme with a "/" in the name, Jekyll fails to generate the site. I don't have an error message right now, unfortunately.

### Steps to reproduce the behavior

1. Create a branch on any remote theme, and ensure "/" is in the branch name.
2. Add `remote_theme: user/themename@the/branch/name` to your site's `_config.yml`
3. Generate the site

### Expected behavior

The site should be generated normally.

### Additional context

Work around this problem by not including slashes in branch names.

**Comment by pdmosses** [comment]
@benbalter This issue is annoying me, and I'd much appreciate it if [the regexp used to match branch names](https://github.com/benbalter/jekyll-remote-theme/blob/master/lib/jekyll-remote-theme/theme.rb#L8) could be [as permissive as GitHub allows](https://docs.github.com/en/get-started/using-git/dealing-with-special-characters-in-branch-and-tag-names#naming-branches-and-tags).

When a user submits a PR that I'd like to test, I need to build the test site using the user's branch. I generally prefer to use `remote_theme` instead of `theme` on the test site (to avoid the need to run `bundle` when testing different PR branches). But when the user's PR branch includes a `/`, I can't use `remote_theme`, and I need to switch to using `theme`.

Is there some reason for `remote_theme`  not to support the use of branches, tags, and commits with _all_ the names that GitHub allows?

BTW, I'm not a Ruby programmer, otherwise I'd submit a PR myself to try and fix this issue.
